#!/bin/sh

if [ -s /Applications/Adobe\ Reader.app ]
then
    version=$(defaults read /Applications/Adobe\ Reader.app/Contents/Info.plist  CFBundleShortVersionString)
	echo "<result>$version</result>"
else
	echo "<result>Not Installed</result>"
fi
