#!/bin/sh

if [ -s /Applications/Audacity/Audacity.app ]
then
    version=`defaults read /Applications/Audacity/Audacity.app/Contents/Info.plist  CFBundleShortVersionString`
	echo "<result>$version</result>"
else
	echo "<result>Not Installed</result>"
fi
