#!/bin/sh

if [ ! -f /Library/Application\ Support/JAMF/Waiting\ Room/Install\ OS\ X\ Yosemite.InstallESD.dmg  ]
then
	echo "<result>Not Installed</result>"
else
	echo "<result>Installed</result>"
fi
