#!/bin/sh

if [ -s /private/var/cocoaDialog.app ]
then
    version=`defaults read /private/var/cocoaDialog.app/Contents/Info.plist  CFBundleShortVersionString`
	echo "<result>$version</result>"
else
	echo "<result>Not Installed</result>"
fi
