#!/bin/sh
if [ -s /Applications/GnuCash/GnuCash.app ]
then
    version=`defaults read /Applications/GnuCash/GnuCash.app/Contents/Info.plist  CFBundleShortVersionString`
	echo "<result>$version</result>"
else
	echo "<result>Not Installed</result>"
fi
