#!/bin/sh

if [ -s /Applications/Google\ Chrome.app ]
then
    version=`defaults read /Applications/Google\ Chrome.app/Contents/Info.plist  CFBundleShortVersionString`
	echo "<result>$version</result>"
else
	echo "<result>Not Installed</result>"
fi
