#!/bin/sh
if [ -s /Library/Application\ Support/LanSchool/student.app ]
then
    version=$(defaults read /Library/Application\ Support/LanSchool/student.app/Contents/Info.plist  CFBundleGetInfoString)
	echo "<result>$version</result>"
else
	echo "<result>Not Installed</result>"
fi
